#!/usr/bin/env python3
"""
Pro Pipeline — Master Orchestrator for DfAM
Takes a vague user request and outputs: model + slicer profile + print report.

Usage:
    python pro_pipeline.py --part bracket --load 10 --material PETG --output-dir ./output
    python pro_pipeline.py --part enclosure --width 100 --pcb-mount --output-dir ./output
    python pro_pipeline.py --part gear --teeth 24 --module 1.5 --output-dir ./output

Requirements:
    pip install trimesh numpy scipy
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
SKILL_DIR = SCRIPT_DIR.parent


def _validate_output_dir(path_str: str) -> str:
    """Ensure output directory does not traverse outside cwd."""
    if ".." in path_str:
        raise ValueError(f"Path traversal not allowed: {path_str}")
    path = Path(path_str).resolve()
    cwd = Path.cwd().resolve()
    if path.is_absolute():
        if not (path == cwd or path.is_relative_to(cwd)):
            raise ValueError(f"Absolute path outside project not allowed: {path_str}")
    if not (path == cwd or path.is_relative_to(cwd)):
        raise ValueError(f"Output must be within project directory: {path_str}")
    return str(path)


def _bounded_float(val, min_v, max_v, name):
    if val is not None and not (min_v <= val <= max_v):
        raise ValueError(f"{name} must be between {min_v} and {max_v}")
    return val


def _bounded_int(val, min_v, max_v, name):
    if val is not None and not (min_v <= val <= max_v):
        raise ValueError(f"{name} must be between {min_v} and {max_v}")
    return val


def run_command(cmd, description):
    """Run a script and capture output."""
    print(f"\n{'='*60}")
    print(f"  STEP: {description}")
    print(f"{'='*60}")
    result = subprocess.run(cmd, capture_output=False, text=True)
    if result.returncode != 0:
        print(f"WARN: Step failed with code {result.returncode}")
    return result.returncode == 0


def generate_report(output_dir, part_type, material, tech, stats):
    """Generate a human-readable print report."""
    report_path = Path(output_dir) / "print_report.md"
    lines = [
        "# DfAM Print Report",
        "",
        f"**Part Type:** {part_type}",
        f"**Material:** {material}",
        f"**Technology:** {tech}",
        f"**Output Directory:** {output_dir}",
        "",
        "## Design Decisions",
        f"- Wall thickness: auto-selected based on load and material",
        f"- Tolerances: applied per {tech} design rules",
        f"- Overhang strategy: ≤ {45 if tech=='FDM' else 30}°",
        "",
        "## Slicer Profile",
        "- Profile generated with autopilot settings",
        "- Review layer height, temperatures, and speeds before printing",
        "",
        "## Estimates",
    ]
    if stats:
        lines.extend([
            f"- Estimated weight: {stats.get('weight_g', 'N/A')} g",
            f"- Estimated cost: ${stats.get('cost_usd', 'N/A')}",
            f"- Estimated time: {stats.get('time_hours', 'N/A')} hours",
        ])
    lines.extend([
        "",
        "## Next Steps",
        "1. Open `profile.ini` in PrusaSlicer / OrcaSlicer / Cura",
        "2. Import `part.stl`, verify orientation",
        "3. Preview G-code, check supports",
        "4. Print a test scale model if dimensions are critical",
        "",
        "---",
        "*Generated by 3D Print Model Generation — Pro Level*",
    ])
    report_path.write_text("\n".join(lines))
    print(f"Report saved: {report_path}")


def main():
    parser = argparse.ArgumentParser(description='DfAM Pro Pipeline')
    parser.add_argument('--part', required=True,
                        choices=['bracket', 'enclosure', 'gear', 'snap_fit',
                                 'heatset_boss', 'tolerance_gauge'])
    parser.add_argument('--material', default='PETG',
                        choices=['PLA', 'PETG', 'ABS', 'ASA', 'TPU', 'Nylon', 'PC'])
    parser.add_argument('--tech', default='FDM', choices=['FDM', 'SLA'])
    parser.add_argument('--printer', default='ender3',
                        choices=['ender3', 'prusa', 'bambu', 'p1s', 'p2s', 'voron'])
    parser.add_argument('--output-dir', default='./output')

    # Bracket params
    parser.add_argument('--width', type=float, default=None)
    parser.add_argument('--height', type=float, default=None)
    parser.add_argument('--depth', type=float, default=None)
    parser.add_argument('--load', type=float, default=5)
    parser.add_argument('--hole-d', type=float, default=None)

    # Enclosure params
    parser.add_argument('--wall', type=float, default=None)
    parser.add_argument('--lid', default='snap')
    parser.add_argument('--pcb-mount', action='store_true')

    # Gear params
    parser.add_argument('--teeth', type=int, default=20)
    parser.add_argument('--module', type=float, default=1.0)
    parser.add_argument('--thickness', type=float, default=5)

    # Snap fit params
    parser.add_argument('--length', type=float, default=30)
    parser.add_argument('--deflection', type=float, default=2)

    # Boss params
    parser.add_argument('--insert', default='M3')

    args = parser.parse_args()

    try:
        args.output_dir = _validate_output_dir(args.output_dir)
    except ValueError as e:
        parser.error(str(e))

    try:
        _bounded_float(args.width, 1, 500, "width")
        _bounded_float(args.height, 1, 500, "height")
        _bounded_float(args.depth, 1, 500, "depth")
        _bounded_float(args.load, 0, 100, "load")
        _bounded_float(args.hole_d, 1, 50, "hole-d")
        _bounded_float(args.wall, 0.1, 50, "wall")
        _bounded_int(args.teeth, 5, 200, "teeth")
        _bounded_float(args.module, 0.1, 10, "module")
        _bounded_float(args.thickness, 0.1, 50, "thickness")
        _bounded_float(args.length, 1, 200, "length")
        _bounded_float(args.deflection, 0.1, 20, "deflection")
    except ValueError as e:
        parser.error(str(e))

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    part_file = out_dir / "part.stl"
    profile_file = out_dir / "profile.ini"

    print(f"\n{'#'*60}")
    print(f"# DfAM PRO PIPELINE")
    print(f"# Part: {args.part} | Material: {args.material} | Tech: {args.tech}")
    print(f"{'#'*60}")

    # ── Step 1: Design ─────────────────────────────────────────────────────
    design_cmd = [sys.executable, str(SCRIPT_DIR / "dfam_designer.py"), args.part]

    if args.part == 'bracket':
        if args.width: design_cmd += ['--width', str(args.width)]
        if args.height: design_cmd += ['--height', str(args.height)]
        if args.depth: design_cmd += ['--depth', str(args.depth)]
        if args.hole_d: design_cmd += ['--hole-d', str(args.hole_d)]
        design_cmd += ['--load', str(args.load)]
    elif args.part == 'enclosure':
        if args.width: design_cmd += ['--width', str(args.width)]
        if args.height: design_cmd += ['--height', str(args.height)]
        if args.depth: design_cmd += ['--depth', str(args.depth)]
        if args.wall: design_cmd += ['--wall', str(args.wall)]
        design_cmd += ['--lid', args.lid]
        if args.pcb_mount: design_cmd += ['--pcb-mount']
    elif args.part == 'gear':
        design_cmd += ['--teeth', str(args.teeth), '--module', str(args.module)]
        if args.thickness: design_cmd += ['--thickness', str(args.thickness)]
    elif args.part == 'snap_fit':
        design_cmd += ['--length', str(args.length), '--deflection', str(args.deflection)]
    elif args.part == 'heatset_boss':
        design_cmd += ['--insert', args.insert]

    design_cmd += ['--material', args.material, '--tech', args.tech, '-o', str(part_file)]

    ok = run_command(design_cmd, "Parametric Design")
    if not ok or not part_file.exists():
        print("ERROR: Design step failed.")
        sys.exit(1)

    # ── Step 2: Validate ───────────────────────────────────────────────────
    validate_cmd = [sys.executable, str(SCRIPT_DIR / "validate_mesh.py"), str(part_file)]
    run_command(validate_cmd, "Mesh Validation")

    # ── Step 3: Slicer Profile ─────────────────────────────────────────────
    profile_cmd = [
        sys.executable, str(SCRIPT_DIR / "slicer_autopilot.py"),
        str(part_file),
        '--material', args.material,
        '--printer', args.printer,
        '-o', str(profile_file)
    ]
    run_command(profile_cmd, "Slicer Profile Generation")

    # ── Step 4: Report ─────────────────────────────────────────────────────
    stats = {}
    # Try to parse stats from profile output (simplified)
    print(f"\n{'='*60}")
    print(f"  STEP: Generate Report")
    print(f"{'='*60}")
    generate_report(out_dir, args.part, args.material, args.tech, stats)

    print(f"\n{'#'*60}")
    print(f"# PIPELINE COMPLETE")
    print(f"# Files in: {out_dir.resolve()}")
    print(f"#   - part.stl")
    print(f"#   - profile.ini")
    print(f"#   - print_report.md")
    print(f"{'#'*60}\n")


if __name__ == '__main__':
    main()
